source /usr/share/fzf/shell/key-bindings.zsh
source /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

autoload -Uz vcs_info
precmd() { vcs_info }
zstyle ':vcs_info:git:*' formats ' (%F{red}%b%f)'
zstyle ':vcs_info:git:*' actionformats ' (%F{red}%b|%a%f)'
setopt PROMPT_SUBST
PROMPT='%(?..%F{red}[%?]%f )%F{green}%n%f ➜ %F{blue}%~%f${vcs_info_msg_0_} '

HISTFILE=~/.zsh_history
HISTSIZE=100000
SAVEHIST=100000
setopt SHARE_HISTORY
setopt APPEND_HISTORY

alias ls='ls --color=auto'
alias ll='ls -al'
